name: Flutter Web CI

on:
  push:
  pull_request:

jobs:
  flutter-web:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Project
        run: flutter analyze

      - name: Enable Web
        run: flutter config --enable-web

      - name: Build Flutter Web
        run: flutter build web